import { useRef } from 'react';

import { useRiftState } from 'riftState';

import { Flex } from '../common/Box';
import UILabel from '../common/UILabel';

import { TermTooltip } from '../Tooltip';

function WalletDisplay() {
  const { mana } = useRiftState();
  const ref = useRef();

  return (
    <Flex
      ref={ref}
      textAlign="right"
      position={['relative', 'absolute']}
      top="20px"
      right={[0, '20px']}
      flexDirection="column"
      zIndex={9}
    >
      <UILabel
        color="cyan"
        fadeIn={600}
        zIndex={0}
        label={
          <TermTooltip
            clickable
            container={ref.current}
            definition="Resource token generated by Crystals."
            id="tt-AMNA"
            offset={{ bottom: 10 }}
            term="Adventure Mana"
            url="https://the-rift.notion.site/Adventure-Mana-99fae9ee86bf42b19f416eac1319e3b8"
          >
            $AMNA
          </TermTooltip>
        }
        labelProps={{ textAlign: 'right' }}
        valueProps={{ display: 'block', minWidth: '100px' }}
      >
        {mana || 0}
      </UILabel>
    </Flex>
  );
}

WalletDisplay.propTypes = {};
WalletDisplay.defaultProps = {};

export default WalletDisplay;
